version: "3.8"

services:
  app:
    container_name: "fastapi_app"
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - database


  database:
    container_name: "database"
    image: bitnami/mongodb
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db


