version: "3.8"

services:
  app:
    container_name: "fastapi_app"
    command: bash -c "uvicorn elevatus_poc.main:app --host 0.0.0.0 --port 8000 --reload"
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always
    networks:
      - web_network
    depends_on:
      - database


  database:
    container_name: "database"
    image: bitnami/mongodb
    ports:
      - "27018:27017"
    networks:
      - web_network
    volumes:
      - ./data:/data/db

networks:
  web_network:
    driver: bridge
